services:
  adguard:
    image: adguard/adguardhome:v0.107.79
    container_name: adguard
    restart: unless-stopped

    ports:
      - "${TAILSCALE_IP}:53:53/tcp"
      - "${TAILSCALE_IP}:53:53/udp"
      - "${TAILSCALE_IP}:3000:3000/tcp"
      - "${TAILSCALE_IP}:8080:80/tcp"

    volumes:
      - "${DATA_DIR}/work:/opt/adguardhome/work"
      - "${DATA_DIR}/conf:/opt/adguardhome/conf"
